### ISSUE TITLE
Doesn't load (in Chrome)

### ISSUE THREAD

**Issue by genne** [onfido/onfido-sdk-web-sample-app#87]
After running `npm run start` and going to https://localhost:8090/ I just get a blank screen and the console shows these errors:

'![image](https://user-images.githubusercontent.com/2142735/98796783-0f4f6100-240c-11eb-9678-113e48cbdd85.png)

**Comment by stefaniacardenas** [comment]
Hi @genne, this sample app currently requires an environment variable in order to request a token from a backend endpoint that we use internally to generate test tokens. In a real life integration, you would have your own server requesting the SDK token, therefore currently this sample app does not reflect the behaviour of a real life integration. I understand that ideal behaviour of the sample app would be to demonstrate an end to end integration, therefore I will change the code so that the app will use its own server to request an `sdk_token`, just as you would do in real life. Thanks for bringing this issue up.

**Comment by swervo** [comment]
I have the same experience as @genne. I'm assuming that you haven't had a chance to make this change yet. Is it possible for you to describe the steps that are required in order to get this working on localhost please?

Something like:

1) Create an account with Onfido (it's not obvious how to do this from the main Onfido website)
2) Create a token using `curl` etc
3) Add this token as an environment variable (should be use .env to do this or something?)

This would be a massive help for me - I have a working knowledge of node.js but I'm by no means an expert. Getting something working is the first step towards understanding how it fits together and what the options are. I would be happy to write it up and submit a PR once I got it working. I've raised an issue on the https://github.com/onfido/onfido-sdk-ui repo on this same subject so apologies for that.
